package com.base.sdk.entity.common

/**
 * 运动类型数据
 */
enum class WmSportType(val id: Int) {

    OUTDOOR_RUNNING(1),      // 户外跑步
    OUTDOOR_WALKING(2),      // 户外健走
    MOUNTAIN_CLIMBING(3),    // 登山
    CROSS_COUNTRY(4),        // 越野
    OUTDOOR_HIKING(3),       // 户外徒步
    INDOOR_RUNNING(3),       // 室内跑步
    OUTDOOR_CYCLING(3),      // 户外骑行
    SMALL_WHEEL_BIKE(3),      // 小轮车
    HUNTING(3),             // 打猎
    SAILING(3),             // 帆船运动
    SKATEBOARDING(3),       // 滑板
    ROLLER_SKATING(3),       // 轮滑
    OUTDOOR_ICE_SKATING(3),   // 户外滑冰
    HORSE_BACK_RIDING(3),     // 马术
    MOUNTAIN_BIKING(3),      // 山地自行车
    INDOOR_CYCLING(3),       // 室内骑行
    FREE_TRAINING(3),        // 自由训练
    BASKETBALL(3),          // 篮球
    SOCCER(3),              // 足球
    PING_PONG(3),            // 乒乓球
    BADMINTON(3),           // 羽毛球
    TENNIS(3),              // 网球
    STRENGTH_TRAINING(3),    // 力量训练
    PILATES(3),             // 普拉提
    INDOOR_WALKING(3),       // 室内走路
    TREADMILL(3),           // 跑步机
    GYMNASTICS(3),          // 体操
    ROWING(3),              // 划船
    JUMPING_JACK(3),         // 开合跳
    ELLIPTICAL(3),          // 椭圆机
    STEPPING(3),            // 踏步
    RIDING(3),              // 骑马
    YOGA(3),                // 瑜伽
    CRICKET(3),             // 板球
    BASEBALL(3),            // 棒球
    BOWLING(3),             // 保龄球
    SQUASH(3),              // 壁球
    SOFTBALL(3),            // 垒球
    VOLLEYBALL(3),          // 排球
    BALLET(3),              // 芭蕾
    STREET_DANCE(3),         // 街舞
    DANCE(3),               // 舞蹈
    FENCING(3),             // 击剑
    KARATE(3),              // 空手道
    BOXING(3),              // 拳击
    JUDO(3),                // 柔道
    WRESTLING(3),           // 摔跤
    TAI_CHI(3),              // 太极
    SHUTTLECOCK(3),         // 毽球
    TAEKWONDO(3),           // 跆拳道
    CROSS_TRAINING(3),       // 交叉训练
    SIT_UPS(3),              // 仰卧起坐
    ABDOMINAL_TRAINING(3),   // 腰腹训练
    LATIN_DANCE(3),          // 拉丁舞
    RUGBY(3),               // 橄榄球
    FIELD_HOCKEY(3),         // 曲棍球
    ROWING_MACHINE(3),       // 划船机
    SKIING(3),              // 滑雪
    ICE_HOCKEY(3),           // 冰球
    VO2MAX(3),              // 最大摄氧量
    WALKING_MACHINE(3),      // 漫步机
    TRACK_AND_FIELD(3),       // 田径
    RELAXATION(3),          // 整理放松
    CROSS_FIT(3),            // 交叉配合
    FUNCTIONAL_TRAINING(3),  // 功能性训练
    FITNESS_TRAINING(3),     // 体能训练
    ARCHERY(3),             // 射箭
    FLEXIBILITY(3),         // 柔韧度
    MIXED_AEROBICS(3),       // 混合有氧
    KICKBOXING(3),          // 自由搏击
    AUSTRALIAN_FOOTBALL(3),  // 澳式足球
    MARTIAL_ARTS(3),         // 武术
    BUILDING_CLIMBING(3),    // 爬楼
    HANDBALL(3),            // 手球
    CURLING(3),             // 冰壶
    SNOWBOARDING(3),        // 单板滑雪
    LEISURE_SPORTS(3),       // 休闲运动
    AMERICAN_FOOTBALL(3),    // 美式橄榄球
    HAND_CRANKED_BIKE(3),     // 手摇车
    FISHING(3),             // 钓鱼
    FRISBEE(3),             // 飞盘
    GOLF(3),                // 高尔夫
    FOLK_DANCE(3),           // 民族舞
    ALPINE_SKIING(3),        // 高山滑雪
    SNOW_SPORTS(3),          // 雪上运动
    RELAXATION_MEDITATION(3),// 舒缓冥想类运动
    CORE_TRAINING(3),        // 核心训练
    FITNESS_GAME(3),         // 健身游戏
    FITNESS_DANCE(3),        // 健身操
    GROUP_GYMNASTICS(3),     // 团体操
    BOXING_DANCE(3),         // 搏击操
    LONG_FIELD_HOCKEY(3),     // 长曲棍球
    FOAM_ROLLER_RELAXATION(3),// 泡沫轴筋膜放松
    HORIZONTAL_BAR(3),       // 单杠
    PARALLEL_BARS(3),        // 双杠
    HULA_HOOP(3),            // 呼啦圈
    DARTS(3),               // 飞镖
    PICKLE_BALL(3),          // 匹克球
    HIIT(3),                // HIIT
    SHOOTING(3),            // 射击
    TRAMPOLINE(3),          // 蹦床
    BALANCE_BIKE(3),         // 平衡车
    ROLLERBLADING(3),       // 溜旱冰
    PARKOUR(3),             // 跑酷
    PULL_UPS(3),             // 引体向上
    PUSH_UPS(3),             // 俯卧撑
    PLANK(3),               // 平板支撑
    ROCK_CLIMBING(3),        // 攀岩
    HIGH_JUMP(3),            // 跳高
    BUNGEE_JUMPING(3),       // 蹦极
    LONG_JUMP(3),            // 跳远
    MARATHON(3),            // 马拉松
    JUMP_ROPE(3)             // 跳绳
}
